from typing import Any, Dict, Type

from fastapi import FastAPI

from app.services import route_registration_runtime as route_registration_runtime_service
from app.services import route_registration_saas as route_registration_saas_service


def register_app_route_bundles(
    app: FastAPI,
    *,
    get_db: Any,
    auth_helpers: Any,
    runtime_saas_helpers: Any,
    market_runtime_helpers: Any,
    runtime_web_helpers: Any,
    runtime_view_helpers: Any,
    runtime_saas_date_helpers: Any,
    runtime_saas_payment_helpers: Any,
    runtime_support_helpers: Any,
    reporting_runtime_helpers: Any,
    saas_dashboard_page_helpers: Any,
    runtime_saas_ui_helpers: Any,
    inventory_metric_helpers: Any,
    ai_conf_helpers: Any,
    validate_webhook_token: Any,
    whatsapp_payload_cls: Type[Any],
    whatsapp_runtime_binding_helpers: Any,
    idempotency_cache: Dict[str, Dict[str, Any]],
    market_cache_ttl_seconds: float,
    dashboard_fragment_news_name: str,
    dashboard_fragment_monitors_name: str,
    dashboard_fragment_inventory_name: str,
    dashboard_fragment_trend_name: str,
    dashboard_fragment_summary_name: str,
    dashboard_fragment_pending_closings_name: str,
    dashboard_fragment_recent_operations_name: str,
    friendly_errors: Dict[int, str],
    logger: Any,
    ui_helpers: Any,
    runtime_saas_form_helpers: Any,
    operation_rule_helpers: Any,
    operation_risk_helpers: Any,
    operation_runtime_helpers: Any,
    whatsapp_session_helpers: Any,
    money: Any,
    guided_flow_states: Any,
    saas_session_cookie: str,
) -> None:
    route_registration_runtime_service.register_runtime_routes_bundle(
        app,
        get_db=get_db,
        auth_helpers=auth_helpers,
        runtime_saas_helpers=runtime_saas_helpers,
        market_runtime_helpers=market_runtime_helpers,
        runtime_web_helpers=runtime_web_helpers,
        runtime_view_helpers=runtime_view_helpers,
        runtime_saas_date_helpers=runtime_saas_date_helpers,
        runtime_saas_payment_helpers=runtime_saas_payment_helpers,
        runtime_support_helpers=runtime_support_helpers,
        reporting_runtime_helpers=reporting_runtime_helpers,
        saas_dashboard_page_helpers=saas_dashboard_page_helpers,
        runtime_saas_ui_helpers=runtime_saas_ui_helpers,
        inventory_metric_helpers=inventory_metric_helpers,
        ai_conf_helpers=ai_conf_helpers,
        validate_webhook_token=validate_webhook_token,
        whatsapp_payload_cls=whatsapp_payload_cls,
        whatsapp_runtime_binding_helpers=whatsapp_runtime_binding_helpers,
        idempotency_cache=idempotency_cache,
        market_cache_ttl_seconds=market_cache_ttl_seconds,
        dashboard_fragment_news_name=dashboard_fragment_news_name,
        dashboard_fragment_monitors_name=dashboard_fragment_monitors_name,
        dashboard_fragment_inventory_name=dashboard_fragment_inventory_name,
        dashboard_fragment_trend_name=dashboard_fragment_trend_name,
        dashboard_fragment_summary_name=dashboard_fragment_summary_name,
        dashboard_fragment_pending_closings_name=dashboard_fragment_pending_closings_name,
        dashboard_fragment_recent_operations_name=dashboard_fragment_recent_operations_name,
        friendly_errors=friendly_errors,
        logger=logger,
    )

    route_registration_saas_service.register_saas_routes_bundle(
        app,
        get_db=get_db,
        auth_helpers=auth_helpers,
        ui_helpers=ui_helpers,
        runtime_support_helpers=runtime_support_helpers,
        saas_helpers=runtime_saas_helpers,
        saas_dashboard_page_helpers=saas_dashboard_page_helpers,
        runtime_saas_payment_helpers=runtime_saas_payment_helpers,
        runtime_saas_date_helpers=runtime_saas_date_helpers,
        runtime_saas_form_helpers=runtime_saas_form_helpers,
        operation_rule_helpers=operation_rule_helpers,
        operation_risk_helpers=operation_risk_helpers,
        operation_runtime_helpers=operation_runtime_helpers,
        whatsapp_session_helpers=whatsapp_session_helpers,
        whatsapp_runtime_binding_helpers=whatsapp_runtime_binding_helpers,
        friendly_errors=friendly_errors,
        whatsapp_payload_cls=whatsapp_payload_cls,
        money=money,
        guided_flow_states=guided_flow_states,
        saas_session_cookie=saas_session_cookie,
    )